# Generated by Django 2.1.1 on 2018-11-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetime',
            name='semesters',
            field=models.TextField(default='Fall'),
            preserve_default=False,
        ),
    ]
