# Generated by Django 2.1.3 on 2018-11-29 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_savedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcourse',
            name='saved_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finder.Course'),
        ),
        migrations.AlterField(
            model_name='savedcourse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
